{
 "title": "JMX prometheus exporter",
 "description": "Complete dashboard using metrics from prometheus JMX exporter, with drill down per job > pod",
 "tags": [ "JVM" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "label_values(job)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_info{job=\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$job\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(jvm_memory_bytes_used{area=\"heap\",job=\"$job\",instance=~\"$instance\"})*100) / sum(jvm_memory_bytes_max{area=\"heap\",job=\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(process_start_time_seconds{job=\"$job\"})*1000"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Used {{instance}}"
    },
    {
     "expr": " jvm_memory_bytes_committed{area=\"heap\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Committed {{instance}}"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"heap\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Max {{instance}}"
    }
   ]
  },
  {
   "title": "Non Heap",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Used  {{instance}}"
    }
   ]
  },
  {
   "title": "PS Eden Space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{job=\"$job\", pool=\"PS Eden Space\",instance=~\"$instance\"}",
     "legendFormat": "Used  {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{job=\"$job\", pool=\"PS Eden Space\",instance=~\"$instance\"}",
     "legendFormat": "Committed  {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_max{job=\"$job\", pool=\"PS Eden Space\",instance=~\"$instance\"}",
     "legendFormat": "Max  {{instance}}"
    }
   ]
  },
  {
   "title": "PS Old Gen",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{job=\"$job\", pool=\"PS Old Gen\",instance=~\"$instance\"}",
     "legendFormat": "Used  {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{job=\"$job\", pool=\"PS Old Gen\",instance=~\"$instance\"}",
     "legendFormat": "Committed  {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_max{job=\"$job\", pool=\"PS Old Gen\",instance=~\"$instance\"}",
     "legendFormat": "Max  {{instance}}"
    }
   ]
  },
  {
   "title": "PS Survivor Space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{job=\"$job\", pool=\"PS Survivor Space\",instance=~\"$instance\"}",
     "legendFormat": "Used  {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{job=\"$job\", pool=\"PS Survivor Space\",instance=~\"$instance\"}",
     "legendFormat": "Committed  {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_max{job=\"$job\", pool=\"PS Survivor Space\",instance=~\"$instance\"}",
     "legendFormat": "Max  {{instance}}"
    }
   ]
  },
  {
   "title": "Metaspace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{job=\"$job\", pool=\"Metaspace\",instance=~\"$instance\"}",
     "legendFormat": "Used {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{job=\"$job\", pool=\"Metaspace\",instance=~\"$instance\"}",
     "legendFormat": "Committed {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_max{job=\"$job\", pool=\"Metaspace\",instance=~\"$instance\"}",
     "legendFormat": "Max {{instance}}"
    }
   ]
  },
  {
   "title": "Compressed Class Space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{job=\"$job\", pool=\"Compressed Class Space\",instance=~\"$instance\"}",
     "legendFormat": "Used {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{job=\"$job\", pool=\"Compressed Class Space\",instance=~\"$instance\"}",
     "legendFormat": "Committed {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_max{job=\"$job\", pool=\"Compressed Class Space\",instance=~\"$instance\"}",
     "legendFormat": "Max {{instance}}"
    }
   ]
  },
  {
   "title": "Code Cache",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{job=\"$job\", pool=\"Code Cache\",instance=~\"$instance\"}",
     "legendFormat": "Used {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{job=\"$job\", pool=\"Code Cache\",instance=~\"$instance\"}",
     "legendFormat": "Committed {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_max{job=\"$job\", pool=\"Code Cache\",instance=~\"$instance\"}",
     "legendFormat": "Max {{instance}}"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "JVM current threads  {{instance}}"
    },
    {
     "expr": "jvm_threads_daemon{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "JVM daemon threads {{instance}}"
    },
    {
     "expr": "jvm_threads_deadlocked{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "JVM deadlocked threads  {{instance}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{gc}}  {{instance}}"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{job=~\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{gc}} {{instance}}"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "loaded  {{instance}}"
    }
   ]
  }
 ]
}